// Generates a real registry.gen.ts (not a bundler virtual module) because themes/index.ts is imported by `bun test`, where a runtime plugin cannot resolve a virtual specifier. Run at dev-server/build/test startup.

import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export function generateContentThemesRegistry(themesDir: string): void {
  // A theme is a top-level file (default.ts) or a folder holding its file plus assets (webbeds/webbeds.ts + logo.svg); scan one level down for the latter.
  const isThemeFile = (f: string) => f.endsWith(".ts") && f !== "index.ts" && f !== "registry.gen.ts";
  const specs: string[] = [];
  for (const entry of readdirSync(themesDir).sort()) {
    const full = join(themesDir, entry);
    if (statSync(full).isDirectory()) {
      for (const f of readdirSync(full).filter((x) => x.endsWith(".ts")).sort()) {
        specs.push(`./${entry}/${f.replace(/\.ts$/, "")}`);
      }
    } else if (isThemeFile(entry)) {
      specs.push(`./${entry.replace(/\.ts$/, "")}`);
    }
  }
  const imports = specs.map((s, i) => `import * as m${i} from "${s}";`).join("\n");
  const mods = specs.map((_, i) => `m${i}`).join(", ");
  const contents = `// AUTO-GENERATED by plugins/content-themes.ts — do not edit; gitignored, regenerated on build/dev/test.
${imports}
const isTheme = (v: any) => v && typeof v === "object" && "id" in v && "template" in v && "fonts" in v;
export const allThemes = [${mods}].flatMap((m) => Object.values(m).filter(isTheme));
`;
  writeFileSync(join(themesDir, "registry.gen.ts"), contents);
}
