// Generates a real registry.gen.ts (not a bundler virtual module) because themes/index.ts is imported by `bun test`, where a runtime plugin cannot resolve a virtual specifier. Run at dev-server/build/test startup.

import { readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

function displayName(id: string): string {
  return id
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

export function generateContentThemesRegistry(themesDir: string): void {
  const ids = readdirSync(themesDir)
    .filter((f) => f.endsWith(".typ"))
    .map((f) => f.replace(/\.typ$/, ""))
    .sort();
  const imports = ids
    .map((id, i) => `import t${i} from "./${id}.typ" with { type: "text" };`)
    .join("\n");
  const entries = ids
    .map(
      (id, i) =>
        `  { id: ${JSON.stringify(id)}, name: ${JSON.stringify(displayName(id))}, template: t${i}, fonts: { assets: ["text"] } },`,
    )
    .join("\n");
  const contents = `// AUTO-GENERATED by plugins/content-themes.ts — do not edit; gitignored, regenerated on build/dev/test.
import type { Theme } from "./index";
${imports}
export const allThemes: Theme[] = [
${entries}
];
`;
  writeFileSync(join(themesDir, "registry.gen.ts"), contents);
}
